### ISSUE TITLE
Add tests.

### ISSUE THREAD

**Issue by jarekwg** [jarekwg/django-apscheduler#1]

**Comment by sunjiali** [comment]
Hi jarekwg,

When i try to follow the steps test the code encounter this issue, I am using python 2.7:
Can you help me take a look?

In [7]: scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-ad1f86cd09ae> in <module>()
----> 1 scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')

/home/sunjiali/workspace1/Timer/Timer/django_apscheduler/jobstores.pyc in __init__(self, pickle_protocol)
     17 
     18     def __init__(self, pickle_protocol=pickle.HIGHEST_PROTOCOL):
---> 19         super().__init__()
     20         self.pickle_protocol = pickle_protocol
     21 

TypeError: super() takes at least 1 argument (0 given)

In [8]:

**Comment by jarekwg** [comment]
Replied to the other issue you opened.

**Comment by jarekwg** [comment]
Done in https://github.com/jarekwg/django-apscheduler/pull/9
