### ISSUE TITLE
Please add register_job changes to pip repository

### ISSUE THREAD

**Issue by eric02138** [jarekwg/django-apscheduler#11]
Looks pip isn't seeing your latest changes to the code (I did a "pip install django_apscheduler" and it didn't come with the register_job function.  Might be a gotcha for other coders.

**Comment by eric02138** [comment]
On second look, register_job seems to wrap the wrong object.  It's wrapping the ABScheduler's BaseSchedule Object, which doesn't look at the DjangoJobStore.  I reverted to the @scheduler decorator.  Beware: the syntax should be @scheduler.scheduled_job, not @scheduler.schedule_job

**Comment by jarekwg** [comment]
Thanks, I've fixed the README to say `@scheduler.scheduled_job` in b2396f365db6ac95a83c388577f5fee8fba774f9. Would you be interested in submitting a PR for the incorrect wrapping?

Cheers,

**Comment by eric02138** [comment]
Thanks for fixing the readme.  Alas, I'm not sure if I understand how register_job is supposed to work.  I may be able to return to this at some point, but right now I'm up against a deadline.

**Comment by sallyruthstruik** [comment]
@eric02138 Fixed. 0.2.2 version in PyPI: https://pypi.python.org/pypi/django_apscheduler/0.2.2
