### ISSUE TITLE
Want a feature that task can be triggered to run instantly

### ISSUE THREAD

**Issue by weaming** [jarekwg/django-apscheduler#16]
I'm using this library to help me manage tasks in django admin.
Now I want a new feature that task can be triggered to run after one click of a button. But I have no idea how to implement it. Any advice?

**Updated:**

I have another 2 table: task, trigger

I add a action in task's admin page, select the action and click 'go' button, the associated function will create a trigger with current time. This new trigger will create a `job` table record to the `django-apscheduler`, and then this job will be handler by `django-apscheduler`.

**Comment by weaming** [comment]
I use the latest apscheduler and `BackgroundScheduler`.

@sallyruthstruik Actually I create a new table name 'trigger' to record trigger info mation, then [added a hook](https://docs.djangoproject.com/en/2.0/topics/signals/) to process django admin save/delete event.

To add instant task, I added a action in django admin for another table name 'task' to fire the action, then the hooked function add a `cron` type to scheduler the task with current time.

Workflow `task --> trigger --> job --> execution`.

**Comment by sallyruthstruik** [comment]
I'll take a look to BackgroundScheduler in the week. 

About your solution, it will be amazing if you provide some code snippets, because it isn't clear for me right now.

**Comment by weaming** [comment]
new table to store information to define them.

**Comment by angeic** [comment]
In my project, I run my job instantly like this:
`    job = scheduler.get_job(job_id)
    job.func(*job.args, **job.kwargs)`
