### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by sunjiali** [jarekwg/django-apscheduler#2]
Hi jarekwg,

When i try to follow the steps test the code encounter this issue, I am using python 2.7:
Can you help me take a look?
In [7]: scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')

TypeError Traceback (most recent call last)
in ()
----> 1 scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')

/home/sunjiali/workspace1/Timer/Timer/django_apscheduler/jobstores.pyc in init(self, pickle_protocol)
17
18 def init(self, pickle_protocol=pickle.HIGHEST_PROTOCOL):
---> 19 super().init()
20 self.pickle_protocol = pickle_protocol
21

TypeError: super() takes at least 1 argument (0 given)

In [8]:

**Comment by jarekwg** [comment]
Hi sunjiali, are you running on Python 2?

This repo is currently python 3 only.

I'm happy to merge PRs that add python2 compatibility.

In this case all that's missing is arguments to the `super()` call:
`super()` -> `super(classname, self)`

**Comment by sunjiali** [comment]
Hi, jarekwg
I just changed super().__init__()-> super(DjangoJobStore,self).__init__() still have error.


In [14]: scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-ad1f86cd09ae> in <module>()
----> 1 scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')

/home/sunjiali/workspace1/Timer/Timer/django_apscheduler/jobstores.pyc in __init__(self, pickle_protocol)
     17     def __init__(self, pickle_protocol=pickle.HIGHEST_PROTOCOL):
     18         super(DjangoJobStore,self).__init__()
---> 19         self.pickle_protocol = pickle_protocol
     20 
     21     def lookup_job(self, job_id):

TypeError: super() takes at least 1 argument (0 given)

In [15]: 

Am I missing something?

**Comment by sunjiali** [comment]
Jarekwg,
Many thanks for your qucik response. It' working now.
