### ISSUE TITLE
Make sure only one worker launches the apscheduler.

### ISSUE THREAD

**Issue by hhyo** [jarekwg/django-apscheduler#21]
just like: [stackoverflow](https://stackoverflow.com/questions/16053364/make-sure-only-one-worker-launches-the-apscheduler-event-in-a-pyramid-web-app-ru?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by sallyruthstruik** [comment]
@hhyo not clear the problem you try to describe. If you don't want several copies of scheduler just use blocking scheduler and separate script/django command. 

I think disallowing multiple workers on library side isn't proper and clear way. But I'm open for discussion)
