### ISSUE TITLE
how can I run task?

### ISSUE THREAD

**Issue by rightx2** [jarekwg/django-apscheduler#24]
I followed the instruction in `README.md` (locate `jobs.py` with `settings.py` and `urls.py` in my project folder).

When I run `python manage.py runserver 0.0.0.0:8001`, the task didn't start!

It is also not registered in admin page, either....

How can I make it run? or registered in admin?

**Comment by sallyruthstruik** [comment]
Do you have any errors in console output?
Can you give contents of jobs.py, settings.py, urls.py and other files you created according to docs?
Can you give pip freeze output?

**Comment by jcass77** [comment]
Closing due to long period of inactivity - please re-open if necessary.
