### ISSUE TITLE
My execution issue

### ISSUE THREAD

**Issue by gaxfor** [jarekwg/django-apscheduler#28]
1. 
![image](https://user-images.githubusercontent.com/11613763/42008866-aa84d22c-7ac2-11e8-986b-2ff5b604bc20.png)

What is the difference between these two?
I run it in urls.py

2.
I also run it using the commands below.

```
class Command(BaseCommand):
  """
  Management command for APScheduler
  """
  def handle(self, *args, **kwargs):
      from scheduler import jobs
```

It registers well with django_apscheduler_djangojob but does not run. How do I resolve this?
(id : rank)
![image](https://user-images.githubusercontent.com/11613763/42008967-4af9b0a6-7ac3-11e8-8d13-67ea506fe9cf.png)

**Comment by sallyruthstruik** [comment]
@gaxfor thank you for issue. Unfortunately, statuses may have some errors, because of structure of scheduler events. I'll think about how I can solve this bug.
