### ISSUE TITLE
How could i migrate based on oracle，the default table name django_apschedular_djangojobexecution exceed  30charachters

### ISSUE THREAD

**Issue by dreamjole** [jarekwg/django-apscheduler#31]
The version is 0.2.12，thanx for help

**Comment by dreamjole** [comment]
anybody can help？

**Comment by jarekwg** [comment]
You can override the table name with the `db_table` Model Meta parameter. As for how to get it in there, I'm not sure what the best approach is, whether it's as easy as defining a proxy or subclassed model, or whether you need to monkeypatch it.. worst case scenario can always fork, at which point you could just rename the model name altogether.
