### ISSUE TITLE
TypeError: remote_cmd() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by mingxiaoxu** [jarekwg/django-apscheduler#32]
when you add a job into scheduler, this job is in a class ,get an error
scheduler.add_job(saltapi.remote_cmd, trigger='interval', start_date=start_datetime, days=days, hours=hours,
                              minutes=minutes, kwargs={"tgt": target, "fun": module, "arg": arg}, id=job_name)

get an error:
TypeError: remote_cmd() missing 1 required positional argument: 'self'

**Comment by jcass77** [comment]
No reference to `remote_cmd` in django_apscheduler or APScheduler itself.

The issue might be related to how the Job was constructed in your code but without more information we won't be able to assist unfortunately.
