### ISSUE TITLE
It seems the interval is ignored. 

### ISSUE THREAD

**Issue by soerendip** [jarekwg/django-apscheduler#39]
It seems the interval is ignored. No matter what I put in there, the job is executed every second. Not, sure whether that is the purpose of 'seconds' cause it is not explained in the readme.

```
import time

from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'djangojobstore')

@register_job(scheduler, "interval", minutes=60, id="job1")
def test_job():
    #time.sleep(10)
    print("I'm the first test job!")
    # raise ValueError("Olala!")

register_events(scheduler)
scheduler.start()
print("Scheduler started!")
```

**Comment by jcass77** [comment]
I think this is documented in upstream APScheduler - have a look at https://apscheduler.readthedocs.io/en/latest/modules/triggers/interval.html?highlight=interval#module-apscheduler.triggers.interval.
