### ISSUE TITLE
Timestamps in Django admin site ignore timezone

### ISSUE THREAD

**Issue by jcass77** [jarekwg/django-apscheduler#42]
The runtime timestamps that are displayed for django-apscheduler in the Django admin site are always rendered using the same ``"%Y-%m-%d %H:%M:%S"`` time format.

This can be confusing as date times rendered elsewhere by standard Django uses the format specified in the [DATE_TIME](https://docs.djangoproject.com/en/2.1/ref/settings/#datetime-format) setting instead, which defaults to ``'N j, Y, P'``.

The current implementation also does not cater for displaying date times in the user's local or preferred format.

As an example, the UCT time ``2018-11-19 06:10:00`` should be displayed as ``Nov. 19, 2018, 8:10:00 a.m.`` if the user's local time is UCT+2, to align with standard Django.

**Comment by arhantpanda** [comment]
Having similar issue.
