### ISSUE TITLE
Negative job execution duration

### ISSUE THREAD

**Issue by hugorodgerbrown** [jarekwg/django-apscheduler#44]
I have just run some test jobs through, and one of them has come back with a negative duration:

<img width="421" alt="screenshot 2018-11-22 at 09 59 43" src="https://user-images.githubusercontent.com/200944/48895650-82392900-ee3d-11e8-943a-de1b5f4c5d23.png">

This should be impossible. I'll take a look at the code in due course, but wanted to log this here for now.

**Comment by jcass77** [comment]
Fixed via #86.
