### ISSUE TITLE
Can not work with uWSGI Mule

### ISSUE THREAD

**Issue by fogmoon** [jarekwg/django-apscheduler#45]
Hi jarekwg,

I use `django-apscheduler` in my `Django` project with `uWSGI`.  When I try use the  [Mule](https://uwsgi-docs.readthedocs.io/en/latest/Mules.html) option, the scheduler just do not work.  

Please check it, Thanks.

`uwsgi.ini`
```
......
# use mule
mule  = cron_jobs.py
```

`cron_jobs.py`

- Workable codes, which can print `Before` and `After` and the job log 
    ```
	print("Before")

	scheduler = BackgroundScheduler()
	# scheduler.add_jobstore(DjangoJobStore(), "default")   <--------  
	register_events(scheduler)
	scheduler.add_job(solve__job, 'interval', seconds=10)
	scheduler.start()

	print("After")

    ```

- Non-workable codes, which just print `Before` twice and do nothing 
	```
	print("Before")

	scheduler = BackgroundScheduler()
	scheduler.add_jobstore(DjangoJobStore(), "default")     <--------  
	register_events(scheduler)
	scheduler.add_job(solve__job, 'interval', seconds=10)
	scheduler.start()

	print("After")
	```

**Comment by jcass77** [comment]
I'm not familiar with Mule but have had good success using a `BlockingScheduler` with a regular Django management command.

Something along the lines of:

```python
class Command(BaseCommand):
    help = "Runs apscheduler."

    def handle(self, *args, **options):
        scheduler = BlockingScheduler()
        scheduler.add_jobstore(DjangoJobStore(), "default")

        scheduler.add_job(
            update_all_account_balances_job,
            trigger=CronTrigger(minute="*/10"),  # Every 10 mins
            id="update_all_account_balances",
            max_instances=1,
            replace_existing=True,
        )
        logger.info("Added job 'update_all_account_balances'.")

        try:

            logger.info("Starting scheduler...")
            scheduler.start()
        except KeyboardInterrupt:
            logger.info("Stopping scheduler...")
            scheduler.shutdown()
            logger.info("Scheduler shut down successfully!")
```

Hope that helps - please re-open if you have more info that could help to pinpoint a bug in django_apscheduler.

**Comment by jcass77** [comment]
Users landing on this issue in future might also want to check out the limitations of using uWSGI with APScheduler that have been documented upstream at https://apscheduler.readthedocs.io/en/latest/faq.html#how-can-i-use-apscheduler-with-uwsgi
