### ISSUE TITLE
为什么一个任务会执行两次，有什么好的办法吗

### ISSUE THREAD

**Issue by haha1808656980** [jarekwg/django-apscheduler#48]
![image](https://user-images.githubusercontent.com/38517004/50469076-de1b4280-09e5-11e9-8781-4a7dbc97cfd6.png)

**Comment by haha1808656980** [comment]
最后一个字段是job_id

**Comment by haha1808656980** [comment]
同一时间执行了两次

**Comment by ZiJun188** [comment]
你好，能问下，我这边执行完任务后，在Mysql数据库里没有相关信息，一直打印 Job with id task-1 not found in database 能帮忙指点下？

**Comment by ZiJun188** [comment]
你好，一个任务执行两次的问题解决了？我也出现这个问题了。没找到好的解决方式。

**Comment by ciciandjojo** [comment]
我这边也是很奇怪，会出现添加了多少个任务就会每次执行任务就执行多少次

**Comment by zdYng** [comment]
@ZiJun188 你这个数据库add_jobstore有问题呗，我改写了这个库，用自己的数据表都可以使用的
![image](https://user-images.githubusercontent.com/17880611/65496914-ef00d200-deeb-11e9-9dab-b28b14e39c3d.png)
![image](https://user-images.githubusercontent.com/17880611/65496945-f922d080-deeb-11e9-9276-8272e4dea5de.png)

**Comment by zdYng** [comment]
# 存储器
redis_store = RedisJobStore(host='192.168.1.143',port='6379')
mysql_store = SQLAlchemyJobStore(url='mysql://root:1@192.168.1.143:3311/test3')
postgres_store = SQLAlchemyJobStore(url='postgresql://postgres:postgres@192.168.1.129:5432')
myjobstores = {
    'redis': redis_store,
    # 'mysql': mysql_store,
    'default': postgres_store,
}

scheduler = BackgroundScheduler(myjobstores)

scheduler.add_jobstore(TaskJobStore(), 'default')

其中TaskJobStore是我自己继承的BaseJobStore方法，主要需要调用自己的数据库表

**Comment by ZiJun188** [comment]
@zdYng 你好，非常感谢回复。我目前改了，我加了一个文件锁，把重复执行的问题解决了，可以正常使用，但是 还有有其它小问题，我这两天整理下，提交我的使用示例，帮忙再看看。我目前用的也是SQLAlchemy，链接的是mysql，但是老是出现  _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away') 数据库断开的问题。但是主体程序是没有出现这个问题的。

**Comment by ZiJun188** [comment]
最近发现这里面问题还是有点，或许是使用不当，需要大佬指导下。这个重复执行的问题，我只是在代码层面解决了，加了一个文件锁，但是觉得有点麻烦。我认为最好还是在框架层面解决，比较好。方便加个微信好友？我的微信号：CrazY110999

才看到，不好意思。




在 2019-09-19 09:54:22，"ciciandjojo" <notifications@github.com> 写道：


我这边也是很奇怪，会出现添加了多少个任务就会每次执行任务就执行多少次

**Comment by zdYng** [comment]
@ZiJun188 我不清楚你的MySQL server has gone away具体是什么情况，可以看一下你配置代码吗？以及你是如何调用django_apscheduler库的。

**Comment by zdYng** [comment]
## 代码截图：
![image](https://user-images.githubusercontent.com/17880611/65567418-d1357a80-df88-11e9-9a47-5c7e44d4e90c.png)
## mysql数据库截图
（1）
![image](https://user-images.githubusercontent.com/17880611/65567481-0215af80-df89-11e9-8846-c806e0c6b4f6.png)

（2）
![image](https://user-images.githubusercontent.com/17880611/65567510-22456e80-df89-11e9-95e6-17d6681c1bc4.png)


这个是我当时自己写的测试django_apscheduler库的例子，以便开发适合自己项目的库，你可以参考一下

**Comment by zdYng** [comment]
@ZiJun188 直接连mysql好像不需要通过SQLAlchemy，你可以看看你的代码有什么不同

**Comment by ZiJun188** [comment]
嗯嗯，好的，我这两天整理下，把相关代码分离出来。提供出来。




At 2019-09-25 11:35:46, "zdYng" <notifications@github.com> wrote:


@ZiJun188 我不清楚你的MySQL server has gone away具体是什么情况，可以看一下你配置代码吗？以及你是如何调用django_apscheduler库的。

**Comment by drunkpig** [comment]
这个工程问题多多。特别是执行历史这块，几乎是个大的混乱存在。执行的job和历史记录对不上号，无法关联，这个库大家不要想着用了。

**Comment by drunkpig** [comment]
核心缺陷是job和job instance 无法建立1对N的关联。当去更新job instance状态的时候，用的却是job_id， 这个job_id无法区分job instance。所以嗝屁。如果要加个job_instance_id呢，这个就得改动apscheduler了。

**Comment by drunkpig** [comment]
> 核心缺陷是job和job instance 无法建立1对N的关联。当去更新job instance状态的时候，用的却是job_id， 这个job_id无法区分job instance。所以嗝屁。如果要加个job_instance_id呢，这个就得改动apscheduler了。

https://github.com/agronholm/apscheduler/pull/436   提了个PR

**Comment by jcass77** [comment]
Cant's speak for @jarekwg but I can unfortunately only provide support for issues that are logged in English.

Please re-open if there is more to be done here.
