### ISSUE TITLE
test job not display in Django admin --django job execution

### ISSUE THREAD

**Issue by Wesly-Yu** [jarekwg/django-apscheduler#49]
django_apscheduler :0.2.13
@register_job(scheduler, "interval", minutes=60, id="job1")
def test_job():
    #time.sleep(10)
    print("I'm the first test job!")
    # raise ValueError("Olala!")

register_events(scheduler)
scheduler.start()
print("Scheduler started!")

![qq 20190115201403](https://user-images.githubusercontent.com/43123294/51180219-c65b1e00-1902-11e9-9bf3-b46925f3aeff.png)
Can't select job name in picture

**Comment by ZiJun188** [comment]
麻烦问下，你这个问题解决了？

**Comment by Wesly-Yu** [comment]
亲，可以在github上把这个问题  提成bug给我吗


------------------ 原始邮件 ------------------
发件人: "ZiJun188"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 凌晨0:53
收件人: "jarekwg/django-apscheduler"<django-apscheduler@noreply.github.com>;
抄送: "1633235633"<1633235633@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jarekwg/django-apscheduler] test job not display in Django admin--django job execution (#49)




麻烦问下，你这个问题解决了？

**Comment by ZiJun188** [comment]
最后我发现，我用周期性执行器（cron， interval） 在数据库表（django_apscheduler_djangojob， django_apscheduler_djangojobexecution）里就有会记录，要是任务是一次性的，在数据库表django_apscheduler_djangojob 会出现，要是任务执行完了，在django_apscheduler_djangojobexecution 就不会出现，而且还会把django_apscheduler_djangojob 对应的数据删掉。

**Comment by Wesly-Yu** [comment]
你先提个bug  在github上吧，有空我们可以一起研究






------------------ 原始邮件 ------------------
发件人: "ZiJun188"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 上午9:53
收件人: "jarekwg/django-apscheduler"<django-apscheduler@noreply.github.com>;
抄送: "1633235633"<1633235633@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jarekwg/django-apscheduler] test job not display in Django admin--django job execution (#49)




最后我发现，我用周期性执行器（cron， interval） 在数据库表（django_apscheduler_djangojob， django_apscheduler_djangojobexecution）里就有会记录，要是任务是一次性的，在数据库表django_apscheduler_djangojob 会出现，要是任务执行完了，在django_apscheduler_djangojobexecution 就不会出现，而且还会把django_apscheduler_djangojob 对应的数据删掉。

**Comment by jcass77** [comment]
Not sure if this was resolved - please re-open in English if there is more to be done here.
