### ISSUE TITLE
Job(with no triggers) not added to store after calling add_job() post scheduler.start()

### ISSUE THREAD

**Issue by arhantpanda** [jarekwg/django-apscheduler#52]
Though a job that is created after `scheduler.start()` is scheduled, it is not added to the DjangoJobStore on the database.

Seeing this in case where the job has no triggers so it can be run on demand.

**Comment by mkoertgen** [comment]
Occurs also when using `DateTrigger`.

**Comment by mkoertgen** [comment]
After digging into the code base it seems that this is by design. Actually, the job is added and removed right away, cf.:

- https://github.com/agronholm/apscheduler/blob/8a174843acb499d7f327cc49efa4e47bdddeb8da/apscheduler/schedulers/base.py#L991

**Comment by jcass77** [comment]
As per the comments above, jobs will only be persisted to the job store if they have a `next execution time`.
