### ISSUE TITLE
 multi-threaded scheduled tasks

### ISSUE THREAD

**Issue by zdYng** [jarekwg/django-apscheduler#53]
Hello author, how can I call up to multi-threaded scheduled tasks by django?

**Comment by zdYng** [comment]
What is the maximum number of threads?

**Comment by zdYng** [comment]
How can I set up an asynchronous scheduler?

**Comment by jcass77** [comment]
I regret that the questions posed above are very general in nature, and beyond the scope of what we can support here.

Apart from the standard Python documentation on the above topics, you might also want to consider using a background task processing library like [Dramatiq](https://dramatiq.io), which makes this much easier.
