### ISSUE TITLE
I want to help you out

### ISSUE THREAD

**Issue by Ab1gor** [jarekwg/django-apscheduler#55]
Hi,
Didn't find your contacts so raised an issue just to let you know that I am open to help you out.

**Comment by jarekwg** [comment]
Hi Ab1gor, 

Pleased to hear!
Shoot me an email to jarekwg@gmail.com and I'll get you set up. :)

Thanks,
Jarek

**Comment by anon314271** [comment]
Hi there, also interested in getting involved in the project.

Is it possible to get templates for PR and Issues?

**Comment by jarekwg** [comment]
^shoot me an email and I'll get you set up. :)

Happy to have someone add PR/Issue templates.

**Comment by jcass77** [comment]
Thank you to everyone that offered their assistance - it is sorely needed.

Not sure if you managed to get hold of @jarekwg but please feel free to submit PR's for any of the remaining issues that you would like to work on and we will be sure to review / merge.
