### ISSUE TITLE
How to shutdown the job scheduler?

### ISSUE THREAD

**Issue by cfoq** [jarekwg/django-apscheduler#59]
Per the apscheduler documentation, the scheduler should be shut down with`scheduler.shutdown()` but I'm not seeing that anywhere within django-apscheduler.  Is there a recommended way to ensure that the scheduler is shutdown gracefully from within Django?

**Comment by jcass77** [comment]
Where and how the scheduler should be shut down is probably a little implementation dependent.

One example (using `BlockingScheduler` and a Django management command) is described in the comments here: https://github.com/jarekwg/django-apscheduler/issues/45#issuecomment-659510676.
