### ISSUE TITLE
remove_job causes exception NoneType object is not iterable

### ISSUE THREAD

**Issue by shehjart** [jarekwg/django-apscheduler#6]
Running into this exception in a caller of remove_job because the job_id does not exist because of which the filter method returns None.

So handling JobLookupError in caller of remove_job doesnt actually report a non-existent job situation.

def remove_job(self, job_id):
        deleted, _ = DjangoJob.objects.filter(id=job_id).delete()
        if deleted == 0:
            raise JobLookupError(job_id)

**Comment by jarekwg** [comment]
Happy to accept PRs.
