### ISSUE TITLE
apscheduler 定时任务结束时不会释放mysql内存资源？

### ISSUE THREAD

**Issue by nswz** [jarekwg/django-apscheduler#60]

**Comment by rettier** [comment]
I have the same issue, but with postgre sql. If a job makes a sql query during its execution a sql connection is kept and it will slowly exceed the connection limit.

**Comment by shuai93** [comment]
mee too.

**Comment by rettier** [comment]
the problem exists because django's connection manager creates a new connection per thread. Every time you access a model from a job, a connection is created for this thread and never cleaned up. We have fixed this for now by wrapping our job functions and calling `django.db.connections.close_all()` at the end. But this should definitely become part of django-apscheduler

**Comment by shuai93** [comment]
yeah, i have way to try. you can put a patch in django orm code like 

```
import logging
from django.db.backends.base import base as django_db_base
try:
    import MySQLdb as mysqldb
except ImportError:
    mysqldb = None

log = logging.getLogger(__name__)

def mysql_connect_patch() -> None:
    _old_ensure_connection = django_db_base.BaseDatabaseWrapper.ensure_connection
    log.info('loading patch enseure connection is available')
    def ensure_connection_with_retries(self: django_db_base.BaseDatabaseWrapper) -> None:
        if self.connection:
            if self.autocommit:
                if mysqldb and isinstance(self.connection, mysqldb.connections.Connection):
                    # log.info('mysqldb ping confirm connection is available')
                    self.connection.ping(True)
        _old_ensure_connection(self)

    django_db_base.BaseDatabaseWrapper.ensure_connection = ensure_connection_with_retries


mysql_connect_patch()
```

this way may be  cause extra database overhead

**Comment by nswz** [comment]
你好棒呀，我什么时候才能向你一样优秀

**Comment by jcass77** [comment]
I think django_apscheduler can probably be better at managing database connections.

Django does have some configuration options for [managing persistent connections](https://docs.djangoproject.com/en/3.0/ref/databases/#persistent-connections) that could help. But this has limited application however and at some point (depending on job duration and throughput) the only viable option is to use a dedicated connection pooler like [pgbouncer](http://www.pgbouncer.org).
