### ISSUE TITLE
task becom zombie task when the task run six times

### ISSUE THREAD

**Issue by slqqq** [jarekwg/django-apscheduler#64]
the first time start django project,it is work well,but while task run about six times,it become zombie task. however i refresh website task run again. anyone have same situation?

**Comment by jcass77** [comment]
Sounds like this might be related to a database connection that times out (and is then refreshed when you submit a new request in Django).

This might be related to #79, which might be muting the timeout errors without you being made aware of them.

**Comment by jcass77** [comment]
This should be fixed via #89, in the sense that you should now at least be seeing the DB connections errors as they occur (if that is indeed what is happening).

Please also take a look at the [caveats](https://github.com/jarekwg/django-apscheduler#caveats) associated with using a `BackgroundScheduler` in a web application.

Closing for now - please re-open if necessary.
