### ISSUE TITLE
timezone issues

### ISSUE THREAD

**Issue by xing-zhang2** [jarekwg/django-apscheduler#66]
Name: django-apscheduler
Version: 0.3.0
Django Version: 2.1.11

Django：settings.py
TIME_ZONE = 'Asia/Shanghai' #old 'UTC'

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'default')

def prematch_all_invoice():
    logger.info('start...')
    logger.info('end...')

scheduler.add_job(prematch_all_invoice, 'cron', hour=18, minute=44, second=00, timezone='Asia/Shanghai')

register_events(scheduler)
scheduler.start()

![image](https://user-images.githubusercontent.com/57209741/70044358-2a5f0180-15fd-11ea-92f2-6addfa0e154e.png)

**Comment by jcass77** [comment]
It is not apparent from the screenshot what the issue is here (apart from the date and time formats differing).

The`job` description shows the timestamp at which the job will next be run again, and `run time sec` shows the timestamp of the previously completed run.

Could you elaborate please?

**Comment by jcass77** [comment]
#86 contains some changes to ensure that Django's `USE_TZ` and `TIME_ZONE` settings are taken into account when passing date times between django_apscheduler and APScheduler.

Please give the lates codebase a try and re-open if you still experience any issues.
