### ISSUE TITLE
django启动时，报错RuntimeWarning: Got OperationalError

### ISSUE THREAD

**Issue by life334** [jarekwg/django-apscheduler#69]
![QQ图片20200305103119](https://user-images.githubusercontent.com/18569086/75942108-7f483780-5ecc-11ea-8585-cd2590834ef8.png)

启动django的时候，控制台报错：
Performing system checks...

D:\workspace\django_venv\venv\lib\site-packages\apscheduler\schedulers\base.py:162: RuntimeWarning: Got OperationalError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_binary'?\x02}q\\0(U\x04argsq\x01)U\x08executorq\x02U\x07defaultq\x03U\\rmax_instancesq\x04K\x01U\x04funcq\x05U\x19cro' at line 1"). Please, check that you have migrated the database via python manage.py migrate
  self._real_add_job(job, jobstore_alias, replace_existing)
System check identified no issues (0 silenced).
March 05, 2020 - 10:28:40

我的django==1.11.11

**Comment by quimey** [comment]
Check that you have migrated the database via python manage.py (and that you added the app to the settings.py INSTALLED_APPS)

**Comment by jcass77** [comment]
Closing due to long period of inactivity - please re-open if necessary.
