### ISSUE TITLE
一个无法逾越的架构性问题导致此项目注定失败

### ISSUE THREAD

**Issue by drunkpig** [jarekwg/django-apscheduler#75]
在更新jobexec 执行记录的时候，那了job_id来做匹配，实际上1个job对应了多个job_exec执行历史。这样当apschedule回调说某个job执行了或者失败了的时候，只有一个job_id，那么忧郁这个job_id在job_exec表里有多个在执行的job实例，到底应该更新那个实例的状态呢？

代码里可以看到django-apscheduler很粗暴滴选择了最后一个，这样等于是随机算法随机对。
如果想让这个框架好用，需要修改底层依赖的apscheduler，这个工作不小，所以作者也很着急找人接盘。
大家散了吧，如果你有支付等项目使用还是自己手撸，那个djang-background-tasks也是bug一堆，不建议用。

**Comment by drunkpig** [comment]
本来想着优化一下，结果一看还要改apscheduler,还是来日方长吧

**Comment by drunkpig** [comment]
I have submit a PR to apschedule to support 1(job):N(job instance) problem. 
 See https://github.com/agronholm/apscheduler/pull/436

**Comment by jcass77** [comment]
I assume this was dealt with in upstream APScheduler - please re-open if there is more to be done here.

**Comment by drunkpig** [comment]
@jcass77 apscheduler 4.0 will support job and job_instance_id。 before that release this issue has no solution.

**Comment by ydf0509** [comment]
> 在更新jobexec 执行记录的时候，那了job_id来做匹配，实际上1个job对应了多个job_exec执行历史。这样当apschedule回调说某个job执行了或者失败了的时候，只有一个job_id，那么忧郁这个job_id在job_exec表里有多个在执行的job实例，到底应该更新那个实例的状态呢？
> 
> 代码里可以看到django-apscheduler很粗暴滴选择了最后一个，这样等于是随机算法随机对。
> 如果想让这个框架好用，需要修改底层依赖的apscheduler，这个工作不小，所以作者也很着急找人接盘。
> 大家散了吧，如果你有支付等项目使用还是自己手撸，那个djang-background-tasks也是bug一堆，不建议用。

你自己不会用怪别人。作者说了单独启动定时任务，python manage.py  xxxx来启动，多看文档吧，作者反复说了要保证只有一个调度器，你是把定时任务和web服务一起启动，如果加上了uwsgi配置多进程等就会那样了。你自己不会用，怪别人。

**Comment by jcass77** [comment]
@ydf0509, please submit your issues reports in English to allow the wider community to assist.

**Comment by drunkpig** [comment]
> > 在更新jobexec 执行记录的时候，那了job_id来做匹配，实际上1个job对应了多个job_exec执行历史。这样当apschedule回调说某个job执行了或者失败了的时候，只有一个job_id，那么忧郁这个job_id在job_exec表里有多个在执行的job实例，到底应该更新那个实例的状态呢？
> > 代码里可以看到django-apscheduler很粗暴滴选择了最后一个，这样等于是随机算法随机对。
> > 如果想让这个框架好用，需要修改底层依赖的apscheduler，这个工作不小，所以作者也很着急找人接盘。
> > 大家散了吧，如果你有支付等项目使用还是自己手撸，那个djang-background-tasks也是bug一堆，不建议用。
> 
> 你自己不会用怪别人。作者说了单独启动定时任务，python manage.py xxxx来启动，多看文档吧，作者反复说了要保证只有一个调度器，你是把定时任务和web服务一起启动，如果加上了uwsgi配置多进程等就会那样了。你自己不会用，怪别人。

我自己撸了一个： https://github.com/drunkpig/django-background-job
