### ISSUE TITLE
Paused job's next_run_time is None

### ISSUE THREAD

**Issue by heng-zhang-20** [jarekwg/django-apscheduler#77]
If a job was paused by Scheduler like this `BackgroundScheduler().pause_job(job_id="5140")`, this job's next_run_time attribution is None, then function next_run_time_sec(self, obj) in `class DjangoJobAdmin()` will raise an error `AttributeError: 'NoneType' object has no attribute 'month'`. Therefor you'd better deal with it like this:
``` 
# djago_apscheduler/admin.py
def next_run_time_sec(self, obj):
    return util.localize(obj.next_run_time)

# here 
def next_run_time_sec(self, obj):
    if obj.next_run_time:
        return util.localize(obj.next_run_time)

**Comment by jcass77** [comment]
It looks like this was fixed in #68, which is included in the recently released [v0.3.1](https://github.com/jarekwg/django-apscheduler/releases/tag/0.3.1).
