### ISSUE TITLE
django.db.utils.IntegrityError: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by MHB1000** [jarekwg/django-apscheduler#78]
Hi, Please help me with this problem.

Full error code:
return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
Job with id test_job not found in database

If I include this line code in the script:
@register_job(scheduler, "interval", seconds=1)
and run it in the Django environment, it runs without issue and the schedule event is correctly recorded in Django Administration under Django ASPscheduler in both the Django Job Executions and Django Jobs database:

However, if a substitute the:
@register_job(scheduler, "interval", seconds=1)
with;
@register_job(scheduler, 'date', run_date=datetime(2020, 7, 13, 8, 7, 00), id="test_job")

Although the event executes correctly, I get the following errors:

**On execution:**
"Job with id gpio_app.scheduler.test_job not found in database
Job with id test_job not found in database
I'm a test job!"

**On python manage.py runserver:**
"Job with id test_job not found in database"

**On python manage.py makemigrations:**
"return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
Job with id test_job not found in database"

Django Administration under Django ASPscheduler in both the Django Job Executions  and Although the schedule is recorded in the Django Jobs database, there is no record of the execution in the Django Job Executions  database.

Any idea what I am doing wrong?

**Comment by jcass77** [comment]
APScheduler [automatically removes jobs](https://github.com/agronholm/apscheduler/blob/7e78cad90ce080825c46de8967d9573e9fc86353/apscheduler/schedulers/base.py#L593-L611) from the job store when they do not have a 'next execution time' scheduled, which triggers django_apscheduler to also [remove the corresponding job](https://github.com/jarekwg/django-apscheduler/blob/c7ce8cdff8057f35d0304c384c29b41bff327d4c/django_apscheduler/jobstores.py#L143-L147) from the database.

This should cause the deletion to `CASCADE` down to deleting the corresponding `DjangoJobExecution` instances for that `DjangoJob` so I am not sure whey you would end up with broken foreign key references.

This might also be related to #79 (i.e. the deletion fails for whatever reason but is muted).

**Comment by jcass77** [comment]
Please take a look at the [caveats](https://github.com/jarekwg/django-apscheduler#caveats) of using APScheduler's `BackgroundScheduler` in a web application.

If that is what you are currently using then it is possible the you have multiple threads / processes getting into race conditions as they try to update the `DjangoJobStore` simultaneously.

The README now contains information on using a `BlockingScheduler` instead, which is much simpler to do safely.

**Comment by MHB1000** [comment]
Many thanks John, I’ll take a look at it.

**Comment by jcass77** [comment]
Closing this for now - please re-open if necessary.
